### ISSUE TITLE
*** NoMethodError Exception: undefined method `pack' for nil:NilClass

### ISSUE THREAD

**Issue by heaven** [zdavatz/spreadsheet#76]
Hi, getting this after upgrade from 0.6.9 to 0.9.6:

```
sheet = Spreadsheet.open(self.src).worksheet(0)
sheet.rows
*** NoMethodError Exception: undefined method `pack' for nil:NilClass
sheet.rows
[#<Spreadsheet::Excel::Row:0x000000070ebb70 ...
```

First time when I call sheet.rows it always fail with the same error. I could email you the xls file I am working with.

Best,
Alex
