### ISSUE TITLE
 Spreadsheet Library fails with Ruby 2.2 preview 1

### ISSUE THREAD

**Issue by marfanjr** [zdavatz/spreadsheet#124]
I'm using Rails 4.2.0 and Ruby 2.2.0preview1.

After install the gem spreadsheet, i've tried to run the rails server but i get this error:

`alias_method': undefined method `height=' for class `Spreadsheet::Row' (NameError)

**Comment by zdavatz** [comment]
Are you sure this is not a Rails issue?

**Comment by marfanjr** [comment]
Yes, i'm sure.

I've tested using Rails 4.2.0 and Ruby 2.1.3 and worked.

Take a look at the full traceback of the error:

/home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:25:in `alias_method': undefined method `height=' for class `Spreadsheet::Row' (NameError)
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:25:in `block in format_updater'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:23:in `each'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:23:in `format_updater'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:58:in `<class:Row>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:19:in `<module:Spreadsheet>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/row.rb:3:in `<top (required)>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/excel/row.rb:2:in `<top (required)>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/excel/worksheet.rb:2:in `<top (required)>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet/excel/reader.rb:10:in `<top (required)>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/spreadsheet-1.0.1/lib/spreadsheet.rb:30:in `<top (required)>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@global/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
	from /home/marfan/Documentos/agivis/gtech/api/config/application.rb:14:in `<top (required)>'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/marfan/.rvm/gems/ruby-2.2.0-preview1@gtech/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by zdavatz** [comment]
please send me a test script with Ruby 2.2.0 and _without_ any Rails dependency. Publish it to gist.github.com and link it here.

**Comment by marcosgugs** [comment]
Hi @zdavatz, I've same problem. 

My test is published here: https://gist.github.com/marcosgugs/53bff34aeea17ec64659

**Comment by zdavatz** [comment]
Does the test work with Ruby 2.2.0?

**Comment by marcosgugs** [comment]
Hi @zdavatz,
I realy sorry for the inconvenience
I updated my ruby version to 2.2.0 and solved my problem.
Thanks for the fast support.

**Comment by zdavatz** [comment]
Good to know! Ruby 2.2.0 is a real Release and Matz promised me more consistency ;).

**Comment by raghavendrarao-nyros** [comment]
I have upgraded my rvm 2.2.0-preview1 . even though i am getting same error 
how can i solve this ...?

:in `alias_method': undefined method `height=' for class `Spreadsheet::Row' (NameError)

**Comment by zdavatz** [comment]
move away from the preview version I guess.

**Comment by raghavendrarao-nyros** [comment]
Hello :) zdavatz thanks for your reply 

present i require ruby-2.2.0 . when i am trying to install rvm 2.2.0 . it automatically 2.2.0-preview1 is getting installed 

i want rvm ruby-2.2.0 stable version . How can i install it ..?

**Comment by zdavatz** [comment]
I personally switched from rvm to rbenv. Works better. ;) - With rvm it must be something like
rvm list
rvm use 2.2.0

**Comment by zdavatz** [comment]
see: https://rvm.io/rubies/default

**Comment by raghavendrarao-nyros** [comment]
I know this. but when i am trying to install like
rvm install ruby-2.2.0 
it automatically installing ruby-2.2.0-preview1 version into my system.
Give me any hint to install only stable version of ruby-2.2.0 other than ruby-2.2.0-perview1 version

**Comment by zdavatz** [comment]
switch to rbenv ;)

**Comment by raghavendrarao-nyros** [comment]
ok thank you for your valuable information
